version: '3.9'
services:
  cupsd:
    image: quphoria/cupsd
    hostname: cupsd
    volumes:
      - ./cupsd.conf:/etc/cups/cupsd.conf
      - ./printers.conf:/etc/cups/printers.conf
      - ./cups_ppd:/etc/cups/ppd
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '631:631'
    environment:
      ADMIN_PASSWORD: cupsadmin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    restart: unless-stopped
